---
title: UsmamAkram
author:
  email: usmanakram232[AT]Gmail
  github: usmanakram232
  name: "Muhammad Usman Akam"
  twitter: usmanakram232

auto: false
safe: false
server: false
server_port: 4000
base-url: /
production_url: "http://usmanakram.me"

source: .
destination: ./_site
plugins: ./_plugins
exclude:
  - README.md
  - util
  - drafts
  - config
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - vendor
  - config.ru
  - unicorn.rb
  - fabfile.py

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: "/posts/:title"

rdiscount:
  extensions:
    - smart