---
title: Wolfie (usman)
author:
  email: github-userName[AT]Gmail
  github: usmanakram232
  name: "Wolfie"
  twitter: usmanakram232

auto: false
safe: false
server: false
server_port: 4000
base-url: /
production_url: "https://usmanakram232.github.io/"

source: .
destination: ./_site
plugins: 
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag
  - some-other-jekyll-plugin
exclude:
  - README.md
  - util
  - drafts
  - config
  - Gemfile
  - Gemfile.lock
  - Procfile
  - Rakefile
  - vendor
  - config.ru
  - unicorn.rb
  - fabfile.py

future: true
lsi: false
pygments: true
markdown: rdiscount
permalink: "/posts/:title"

rdiscount:
  extensions:
    - smart
